// This file is part of Basilisk.

// Copyright (C) 2020-2023  Intergalactic, Limited (GIB).
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `cumulus_pallet_xcmp_queue`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-12-06, STEPS: `10`, REPEAT: `30`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `bench-bot`, CPU: `Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// target/release/basilisk
// benchmark
// pallet
// --chain=dev
// --steps=10
// --repeat=30
// --wasm-execution=compiled
// --heap-pages=4096
// --template=.maintain/pallet-weight-template-no-back.hbs
// --pallet=cumulus-pallet-xcmp-queue
// --output=weights-1.1.0/xcmp_queue.rs
// --extrinsic=*

#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

use cumulus_pallet_xcmp_queue::weights::WeightInfo;

pub struct BasiliskWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for BasiliskWeight<T> {
	/// Storage: `XcmpQueue::QueueConfig` (r:1 w:1)
	/// Proof: `XcmpQueue::QueueConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_config_with_u32() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1594`
		// Minimum execution time: 8_755_000 picoseconds.
		Weight::from_parts(8_941_000, 1594)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `XcmpQueue::QueueConfig` (r:1 w:1)
	/// Proof: `XcmpQueue::QueueConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_config_with_weight() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1594`
		// Minimum execution time: 8_896_000 picoseconds.
		Weight::from_parts(9_059_000, 1594)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `XcmpQueue::QueueConfig` (r:1 w:0)
	/// Proof: `XcmpQueue::QueueConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::QueueSuspended` (r:1 w:0)
	/// Proof: `XcmpQueue::QueueSuspended` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::DeferredQueueSuspended` (r:1 w:0)
	/// Proof: `XcmpQueue::DeferredQueueSuspended` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::DeferredIndices` (r:1 w:1)
	/// Proof: `XcmpQueue::DeferredIndices` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::DeferredMessageBuckets` (r:3 w:3)
	/// Proof: `XcmpQueue::DeferredMessageBuckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::CounterForOverweight` (r:1 w:1)
	/// Proof: `XcmpQueue::CounterForOverweight` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OverweightCount` (r:1 w:1)
	/// Proof: `XcmpQueue::OverweightCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::Overweight` (r:60 w:60)
	/// Proof: `XcmpQueue::Overweight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[1, 3]`.
	fn service_deferred(b: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6242 + b * (324357 ±0)`
		//  Estimated: `9707 + b * (373857 ±0)`
		// Minimum execution time: 33_142_672_000 picoseconds.
		Weight::from_parts(33_268_386_000, 9707)
			// Standard Error: 602_125_184
			.saturating_add(Weight::from_parts(15_702_864_393, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().reads((21_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((21_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 373857).saturating_mul(b.into()))
	}
	/// Storage: `XcmpQueue::DeferredMessageBuckets` (r:1 w:1)
	/// Proof: `XcmpQueue::DeferredMessageBuckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[1, 20]`.
	fn discard_deferred_bucket(m: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `219 + m * (16216 ±0)`
		//  Estimated: `3683 + m * (16216 ±0)`
		// Minimum execution time: 1_281_948_000 picoseconds.
		Weight::from_parts(243_099_051, 3683)
			// Standard Error: 419_944
			.saturating_add(Weight::from_parts(1_090_047_884, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 16216).saturating_mul(m.into()))
	}
	/// Storage: `XcmpQueue::DeferredMessageBuckets` (r:1 w:1)
	/// Proof: `XcmpQueue::DeferredMessageBuckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[1, 20]`.
	fn discard_deferred_individual(m: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `219 + m * (16216 ±0)`
		//  Estimated: `3683 + m * (16216 ±0)`
		// Minimum execution time: 1_341_620_000 picoseconds.
		Weight::from_parts(105_527_197, 3683)
			// Standard Error: 366_172
			.saturating_add(Weight::from_parts(1_214_179_345, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 16216).saturating_mul(m.into()))
	}
	/// Storage: `XcmpQueue::DeferredIndices` (r:1 w:1)
	/// Proof: `XcmpQueue::DeferredIndices` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::DeferredMessageBuckets` (r:1 w:1)
	/// Proof: `XcmpQueue::DeferredMessageBuckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[1, 20]`.
	fn try_place_in_deferred_queue(m: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (16216 ±0)`
		//  Estimated: `9691 + m * (15020 ±55)`
		// Minimum execution time: 107_001_000 picoseconds.
		Weight::from_parts(123_947_871, 9691)
			// Standard Error: 202_249
			.saturating_add(Weight::from_parts(6_781_886, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(Weight::from_parts(0, 15020).saturating_mul(m.into()))
	}
}
