
name: Deploy docs to GitHub pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: codota/toolchain@00a8bf2bdcfe93aefd70422d3dec07337959d3a4
      with:
        profile: minimal

    - name: Generate docs
      run: |
        cargo doc --workspace --all-features --release --no-deps --document-private-items --target-dir ./docs

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd docs/
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy docs'


    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./docs